export const interests = [
  '90s Kid',
  'Harry Potter',
  'SoundCloud',
  'Spa',
  'Self Care',
  'Heavy Metal',
  'House Parties',
  'Gin Tonic',
  'Gymnastics',
  'Hapkido',
  'Hot Yoga',
  'Basketball',
  'Slam Poetry',
  'Home workout',
  'Theater',
  'Cafe hopping',
  'Aquarium',
  'Sneaker',
  'Instagram',
  'Hot Springs',
  'Walking',
  'Running',
  'Tralvel',
];
